name: open_meteo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  bloc: ^9.2.0
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  go_router_builder: ^4.2.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
